### ISSUE TITLE
Process Oriented & Pausable Simulation

### ISSUE THREAD

**Issue by PatatasDelPapa** [elshize/simrs#1]
Hi great work! I'm trying to write my own library but this one is more advanced that mine and your desing seems better too I quite like it but I need to abstract it more to be usable for me.

I need to provide a Process Oriented Simulation where the only events that can happen are (roughly defined as) Hold(t) where t is a time, Passivate(self) and Activate(component). The idea is that the user have to define a function for each component where it can call those 3 operations.

Hold causes the function to stop until the event is realiced and the simulated time advance the specified t continuing the execution from where the hold was called. Passivate makes the component to sleep (not continuing its execution / not producing more events) until another component Activate it.

the function defined for the user can run (is usually) a infinite loop until either break itself or surpass the indicated maximum simulated time.
example
```rust
fn run_component() {
    loop {
        hold(5); // the execution of this function should pause here until this complete.
        // and resume here after it does.
        passivate() // Then it pauses here until someone else activate it.
        /* do more work calling hold, passivate, activate */
        /* change states, etc */
    }
}
```
I'm wondering if what I'm trying to acomplish is possible with this library or if some changes are required.

PD: I've read your article and some of your code there is mixed with the one in your library.
For example you defined a struct State with values
```rust
struct State {
    values: std::containers::HashMap<usize, Box<dyn std::any::Any>>,
}
```
but in the methods you access self.store and there's no store.
```rust
impl State {
    #[must_use = "Discarding key results in leaking inserted value"]
    pub fn insert<V: 'static>(&mut self, value: V) -> Key<V> {
        let id = Self::generate_next_id();
        self.store.insert(id, Box::new(value));
        Key::new(id)
    }
```
So I decided to see the real code for State and there's a store there
```rust
pub struct State {
    store: HashMap<usize, Box<dyn Any>>,
    queues: HashMap<usize, Box<dyn Any>>,
    next_id: usize,
}
```

**Comment by elshize** [comment]
Thanks for pointing out the inconsistencies in the article. I was trying to simplify things there, but clearly made some mistakes. I'll make sure to fix these soon.

As for your problem, I think what you really want is [generators](https://doc.rust-lang.org/beta/unstable-book/language-features/generators.html). This is similar to how SimPy does it. The downside of generators is that they're quite experimental in Rust (only nightly). There is a library that emulates generators with async/await and futures called [genawaiter](https://docs.rs/genawaiter/0.99.1/genawaiter/) but I don't know enough about it to say how useful it is.

Emulating something like this with `simrs` would be kind of awkward. You could probably write a proc macro that will generate something like:

```rust
fn process_event(event: Event, ...) {
    match event {
        Event::Step1 => { ... }
        Event::Step2 => { ... }
        Event::Step3 => {
            ...
            scheduler.schedule(Event::Step1);
        }
    }
}
```

But then you'd have that constraint of not being able to share any variables across `hold`/`passivate` boundaries. At this point, you might as well embrace event-driven simulation instead.

I don't know your requirements, but I think SimPy might fit your case best. Unless it's very resource intensive.

**Comment by PatatasDelPapa** [comment]
It's an investigation of sorts, write my own implementation of a simulation library in Rust and see how it compare to similar ones in other languages. I don't really have limitations outside of it have to be written in Rust.

**Comment by PatatasDelPapa** [comment]
Thanks for the insight. I'll close this.

**Comment by PatatasDelPapa** [comment]
I have manage to create a struct capable of holding generators with any kind of function inside them. The problem with generators is that they own whatever they use by the duration of the generator, so the generator themself can't use a &mut State or &mut Scheduler as they will hold it for the duration of its existence. They can however be resumed with an arbitrary value and they can yield

**Comment by PatatasDelPapa** [comment]
I have managed to create a struct capable of holding a generator with any kind of function inside of it using genawaiter. The restrictions are that the generators have to share the same type for Yield, Resume and Completion, not saying that Y,R,C have to be the same type (as Y=R=C), only that Y, R and C have to independently be same across all generators.
```rust
use std::{future::Future, pin::Pin};
use genawaiter::sync::{Co, Gen, GenBoxed};

struct Container<Y, R, C> {
    inner: Vec<GenBoxed<Y, R, C>>,
}

impl<Y, R, C> Container<Y, R, C> {
    fn add_generator_fn<F>(&mut self, producer: impl FnOnce(Co<Y, R>) -> F)
    where
        F: Future<Output = C> + Send + 'static,
    {
        self.inner.push(Gen::new_boxed(|co| producer(co)));
    }
    fn add_generator(&mut self, gen: Gen<Y, R, Pin<Box<dyn Future<Output = C> + Send>>>) {
        self.inner.push(gen);
    }
}

impl<Y, R, C> Default for Container<Y, R, C> {
    fn default() -> Self {
        Self {
            inner: Default::default(),
        }
    }
}
```
And here a little example that it works
```rust
async fn my_producer(kind: &str, co: Co<()>) {
    println!("Iniciando {}", kind);
    co.yield_(()).await;
    for i in 0..3 {
        println!(
            "{} ha sido llamado {} {}",
            kind,
            i + 1,
            if i == 0 { "vez" } else { "veces" }
        );
        co.yield_(()).await;
    }
    println!("{} Finaliza", kind);
}

fn main() {
    let mut my_generator_a = Gen::new_boxed(|co| my_producer("A", co));
    let mut my_generator_b = Gen::new_boxed(|co| my_producer("B", co));
    let mut my_generator_c = Gen::new_boxed(|co| my_producer("C", co));

    let mut container = Container::<(), (), ()>::default();

    container.add_generator(my_generator_a);
    container.add_generator(my_generator_b);
    container.add_generator(my_generator_c);
    container.add_generator_fn(|co| my_producer("D", co));
}
```
I was planning to include this struct to the library so when a component is created, its generator have to be included too then when the component have to execute instead it `.resume()` (or `resume_with(value)`) the generator. The problem is that the generators will own whatever they use for the duration of the generator, so they can't have access to the &mut State or &mut Scheduler as the others can't then have access to them. I'm considering what to do, try doing some things with yield and resume_with, using channels but I'm not really sure how to continue or if it's feasible

**Comment by elshize** [comment]
You could try using something like `Rc<RefCell<State>>` instead. But really, once you go the process route, then much of the way a simulation works changes. I think what you really want is to communicate through that return value. Say, you return all process IDs you want to wake up at given times, possibly with some payload, and you wake them up by passing that payload in. Then, each process can have its own mutable data. You might want to take some inspiration from SimPy, especially from their resource sharing approach: https://simpy.readthedocs.io/en/latest/simpy_intro/shared_resources.html

I guess what I'm really trying to say is you shouldn't get attached to whatever type of interface I came up with because your approach is fundamentally different and thus might need a different way of process interaction and sharing resources.

The real challenge in your case would be to come up with a good type to yield and to pass to the processes. Without giving it too much though, I can imagine something like:

```rust
struct YieldResult { // or some other, better, name
    process_id: ProcessId,
    time: Duration,
    payload: Payload,
}
```

and maybe you actually yield `Vec<YieldResult>` so you can wake up none, one, or more processes.

In a simplest case, `Payload` can be a simple wrapper over `Any`, and the process itself must downcast it to whatever it expects, or even can expect more than one type and decide what to do based on which one works.

I think that makes sense, but I'm not sure :sweat_smile:

**Comment by PatatasDelPapa** [comment]
I found this library inspired by SimPy called [Desim](https://crates.io/crates/desim) It's mostly what I need but the keys are simply integers and it's using the generator feature directly so I think I'm gonna adapt it to use genawaiter instead so it compile on stable and change all those keys with equivalent to the ones in this library (type-safe keys).

**Comment by elshize** [comment]
Great, good luck and let me know how it goes.
