### ISSUE TITLE
Stability of test_event_entry_debug

### ISSUE THREAD

**Issue by PatatasDelPapa** [elshize/simrs#18]
on scheduler.rs at line 183 there's a test called `test_event_entry_debug()` that compares the debug text output of a `EventEntry` against a hard coded string but [The docs of Debug](https://doc.rust-lang.org/stable/std/fmt/trait.Debug.html#stability) says that 

> Derived Debug formats are not stable, and so may change with future Rust versions. 

That makes me think that it can be a problem having a test that depends on the text output of a derived debug implementation.

**Comment by elshize** [comment]
@PatatasDelPapa thanks, that's a good point. Sorry for the very late reaction, it has been a crazy busy period of time for me.

Removed the test in #19
