### ISSUE TITLE
[Docs] Simulation example doesn't use Simulation

### ISSUE THREAD

**Issue by PatatasDelPapa** [elshize/simrs#2]
At the Simulation part of the [docs](https://docs.rs/simrs/0.1.0/simrs/#simulation) there's an example that create some struct event and impl component for some others but nowhere in the example there's any use of Simulation to run them. Did I misunderstand the example or it's imcomplete?

**Comment by elshize** [comment]
I added usage to the docs but it is not yet populated to docs.rs. You can either open docs locally or I also added it in the `examples` directory.
